apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx2-deploy
spec: #아래는 ReplicaSet 설정
  replicas: 3
  selector: # 아래의 라벨 개수를 확인하여 관리
    matchLabels:
      app: webserver2
  template: # 아래는 Pod 구성
    metadata:
      name: my-webserver2
      labels:
        app: webserver2
    spec: # 아래 부분은 컨테이너 구성 내용
      containers:
      - name: my-webserver2
        image: nginx
        ports:
        - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: nginx2-lb
spec:
  ports:
  - name: web2-port
    port: 80
  selector:
    app: webserver2
  type: LoadBalancer












